apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-jugad-backend
  labels:
    app: job-jugad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-jugad
  template:
    metadata:
      labels:
        app: job-jugad
    spec:
      containers:
        - name: job-jugad
          image: job-jugad:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
